### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Draminha** [CooLowbro/Addons-TOS#1]
Failed to install addon. Please contact CooLowbro.

**Comment by CooLowbro** [comment]
Which addon?

**Comment by Draminha** [comment]
Oh sorry, it's Isabela's addon.

Good Bye Isabela

**Comment by CooLowbro** [comment]
I could not reproduce this error. Could you take a photo or video of the error?

**Comment by CooLowbro** [comment]
I just solved the issue.
Could you try it now?

**Comment by Draminha** [comment]
everything works fine now, Thx!
