### ISSUE TITLE
Error in addon Buff Shop EX

### ISSUE THREAD

**Issue by crismorais** [CooLowbro/Addons-TOS#2]
Please fix the aaddon!
problem:

You can set fixed prices for your buffs and the store name too. Just type /buffshop for further help

Available version: v1.0.0
Failed to install addon. Please contact CooLowbro.

**Comment by crismorais** [comment]
?

**Comment by CooLowbro** [comment]
I could not reproduce this error. Could you take a photo or video of the error?

**Comment by crismorais** [comment]
Hello, I have nothing to reproduce! It's like I said it does not install and gives the error I said. All addons I can install, except this one. Other people also try but can not.
![erro buff](https://cloud.githubusercontent.com/assets/27377858/25104771/08df45f6-2398-11e7-848c-61eaa192cffb.jpg)

**Comment by CooLowbro** [comment]
Thanks for your patience. 
Could you try it now?
